CREATE SCHEMA talk2nature;
REVOKE ALL ON SCHEMA talk2nature FROM PUBLIC;
SET LOCAL search_path=talk2nature,pg_catalog;
CREATE TABLE schema_version (singleton INTEGER PRIMARY KEY CHECK(singleton=1), version INTEGER NOT NULL);
INSERT INTO schema_version VALUES(1,1);
CREATE TABLE owner (singleton INTEGER PRIMARY KEY CHECK(singleton=1), subject TEXT NOT NULL);
CREATE TABLE challenges (digest TEXT PRIMARY KEY, expires BIGINT NOT NULL);
CREATE TABLE sessions (digest TEXT PRIMARY KEY, subject TEXT NOT NULL, csrf TEXT NOT NULL, expires BIGINT NOT NULL);
CREATE TABLE observations (id TEXT PRIMARY KEY, payload TEXT NOT NULL, state TEXT NOT NULL, version INTEGER NOT NULL DEFAULT 1, created BIGINT NOT NULL);
CREATE TABLE releases (id TEXT PRIMARY KEY, members TEXT NOT NULL, fingerprint TEXT NOT NULL, revoked INTEGER NOT NULL DEFAULT 0, created BIGINT NOT NULL);
CREATE TABLE audit (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, action TEXT NOT NULL, target TEXT NOT NULL, created BIGINT NOT NULL);
CREATE TABLE evidence_versions (key TEXT NOT NULL, fingerprint TEXT NOT NULL, payload TEXT NOT NULL, PRIMARY KEY(key,fingerprint));
CREATE TABLE evidence_catalog (key TEXT PRIMARY KEY, kind TEXT NOT NULL, title TEXT NOT NULL, fingerprint TEXT NOT NULL, active INTEGER NOT NULL DEFAULT 1, FOREIGN KEY(key,fingerprint) REFERENCES evidence_versions(key,fingerprint));
CREATE TABLE studies (id TEXT PRIMARY KEY, payload TEXT NOT NULL, fingerprint TEXT NOT NULL, state TEXT NOT NULL, version INTEGER NOT NULL DEFAULT 1, created BIGINT NOT NULL);
CREATE TABLE study_evidence (study_id TEXT NOT NULL REFERENCES studies(id), evidence_key TEXT NOT NULL, fingerprint TEXT NOT NULL, PRIMARY KEY(study_id,evidence_key), FOREIGN KEY(evidence_key,fingerprint) REFERENCES evidence_versions(key,fingerprint));
CREATE TABLE study_sessions (id TEXT PRIMARY KEY, study_id TEXT NOT NULL REFERENCES studies(id), payload TEXT NOT NULL, state TEXT NOT NULL, version INTEGER NOT NULL DEFAULT 1, created BIGINT NOT NULL);
CREATE TABLE observation_links (observation_id TEXT PRIMARY KEY REFERENCES observations(id), study_session_id TEXT NOT NULL REFERENCES study_sessions(id));
REVOKE ALL ON ALL TABLES IN SCHEMA talk2nature FROM PUBLIC;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA talk2nature FROM PUBLIC;
