"""Public video and contribution views, without third-party requests on page load."""
import re


def build_hub(page, url, esc, sources, notes):
    source_map = {s['id']: s for s in sources}
    note_map = {n['slug']: n for n in notes}
    videos = [s for s in sources if 'media' in s]
    cards = []
    for source in videos:
        m = source['media']
        if m['context_id'] not in source_map or any(slug not in note_map for slug in m['related_notes']):
            raise ValueError('Video has an unresolved source or related note')
        if m['provider'] == 'youtube':
            if not re.fullmatch(r'[A-Za-z0-9_-]{11}', m['video_id']):
                raise ValueError('Invalid YouTube video ID')
            if source['url'] != 'https://www.youtube.com/watch?v=' + m['video_id']:
                raise ValueError('Video identity does not match its link')
            player = f'<div class="video-player" data-video-id="{m["video_id"]}" data-video-title="{esc(source["title"])}"><button type="button" class="video-load"><span aria-hidden="true">▶</span> Load YouTube player<span class="video-load-note">Connects to YouTube · no autoplay</span></button></div>'
        else:
            player = '<div class="video-player video-external"><span aria-hidden="true">↗</span><p>Watch on the publisher’s website</p></div>'
        related = ' · '.join(f'<a href="{url("research/"+slug+"/")}">{esc(note_map[slug]["title"])}</a>' for slug in m['related_notes'])
        context = source_map[m['context_id']]
        extra = ''.join(f'<p><a href="{esc(source_map[i]["url"])}">{esc(source_map[i]["title"])}</a></p>' for i in m.get('extra_source_ids', []))
        search = ' '.join([source['title'],m['creator'],m['category'],source['description'],m['watch_for']]).lower()
        cards.append(f'''<article class="video-card" id="video-{source['id']}" data-category="{esc(m['category'])}" data-video-search="{esc(search)}">{player}<div class="video-copy"><p class="eyebrow">{esc(m['category'])}</p><h2>{esc(source['title'])}</h2><p class="video-by">By <a href="{esc(m['creator_url'])}">{esc(m['creator'])}</a></p><p>{esc(source['description'])}</p><p><strong>A question to take with you:</strong> {esc(m['watch_for'])}</p><p><a class="text-link" href="{esc(source['url'])}">Watch on {'YouTube' if m['provider']=='youtube' else 'Cornell Video'} ↗</a></p><details><summary>Source, review depth & related reading</summary><p>{esc(m['review_depth'])} Checked {esc(source['checked'])}.</p><p><a href="{esc(context['url'])}">Publisher context: {esc(context['title'])} ↗</a></p>{extra}<p>{related}</p></details></div></article>''')
    options = ''.join(f'<option>{esc(c)}</option>' for c in sorted({s['media']['category'] for s in videos}))
    page('watch/', 'Watch and learn: animal communication research videos', 'Researcher talks, official films and practical bioacoustics tutorials with attribution, related reading and clear limits.', f'''
<section class="page-intro section watch-intro"><p class="eyebrow">THE WATCHING ROOM</p><h1>Meet the questions.<br><em>Hear from the people.</em></h1><p class="lede">Research talks, field stories and tools worth learning from. Every video has a reason to be here and a path back to the evidence.</p><div class="actions"><a class="text-link" href="{url('research/starting-points/')}">Follow a reading path →</a><a class="text-link" href="{url('contribute/source/')}">Suggest a video or source →</a></div><p class="quiet">{len(videos)} curated videos · Publisher descriptions and identities checked; full videos have not been reviewed. Films and talks are context, not independent scientific validation.</p></section>
<section class="section video-browser"><div class="filters"><div><label for="video-search">Find a topic or creator</label><input id="video-search" type="search" placeholder="Try whales, bats, models…"></div><div><label for="video-category">Choose a path</label><select id="video-category"><option value="all">All videos</option>{options}</select></div></div><div class="library-results-bar"><p id="video-count" role="status">{len(videos)} videos</p><button id="video-reset" type="button" hidden>Clear video filters</button></div><p class="quiet">Players load only when you choose. Loading connects to YouTube, which can receive technical data about your visit. Use headphones away from animals. Each video also has a direct link if embedding is unavailable. No video files are copied or hosted here.</p><div class="video-grid">{''.join(cards)}</div><p id="video-empty" hidden>No videos match. Clear the filters or suggest a source we are missing.</p></section>''', active='research/', extra_head=f'<script type="module" src="{url("assets/hub.js")}"></script>')
    page('contribute/source/', 'Contribute a source or research question', 'Prepare a public source suggestion, correction or research question for the Talk2Nature community on GitHub.', f'''
<article class="article section"><a class="back-link" href="{url('contribute/')}">← Ways to participate</a><p class="eyebrow">BUILD THE LIBRARY TOGETHER</p><h1>Bring one<br><em>useful question.</em></h1><p class="lede">Suggest a paper, dataset, tool or video. Explain why it matters, challenge a claim, or ask about a method.</p><p>Draft below, then review it on GitHub. You choose whether to post it publicly. No account is needed to draft; a GitHub account is needed to post or join the conversation.</p><p class="quiet">Keep recordings, contact details, credentials and sensitive locations out of this form. Nothing is sent while you type. Clicking the GitHub link sends your draft there; posting is a separate step. Drafts are not saved automatically.</p>
<form id="source-proposal" class="proposal-form"><label>Contribution type<select name="kind"><option>Source suggestion</option><option>Correction</option><option>Research question</option><option>Help with a task</option></select></label><label>Short title<input name="title" maxlength="100" required placeholder="What would you like us to examine?"></label><label>Public source or relevant page<input name="url" type="url" maxlength="350" required placeholder="https://…"></label><label>What did you review?<select name="depth"><option>Title or publisher description</option><option>Abstract</option><option>Selected methods or video sections</option><option>Full paper or full video</option><option>Code or data documentation</option><option>Independent reproduction</option></select></label><label>Why it matters / your question<textarea name="reason" rows="5" maxlength="600" required placeholder="Describe the finding or question, what remains uncertain, and how it could help. Include creator attribution for a video."></textarea></label><button class="button" type="submit">Preview my contribution</button><p id="proposal-error" role="alert"></p></form>
<section id="proposal-preview" hidden><h2>Your draft</h2><pre id="proposal-body"></pre><a id="proposal-link" class="button" rel="noreferrer" href="https://github.com/Metivity/talk2nature/issues/new">Review on GitHub ↗</a><p class="quiet">This does not submit a post. Review it, sign in if needed, then choose Submit new issue on GitHub. Other contributors can discuss it in the issue’s comments.</p></section>
<h2>How a contribution becomes part of the hub</h2><ol class="readable-list"><li>Check existing notes and open issues to avoid duplicates.</li><li>Propose a source, question or correction with evidence and attribution.</li><li>Discuss its scope and limitations in the public issue. Maintainers check provenance and reuse terms.</li><li>An accepted change goes through a reviewed repository change before appearing on the site. A suggestion is not scientific endorsement.</li></ol><p><a href="https://github.com/Metivity/talk2nature/issues">Browse open conversations and tasks ↗</a> · <a href="{url('research/')}">Search the library</a></p><noscript><p>The draft helper needs JavaScript. You can instead open an issue directly using the repository’s source or research-question templates.</p></noscript></article>''', extra_head=f'<script type="module" src="{url("assets/hub.js")}"></script>')
